#!/bin/bash
#
#
#	Menu de Para Automatizar o Uso do Sistema.
#
#
#colors
BPTH="./"
echo -ne "				CHOOSE MINER
				------------------------------
			Option          Description                  
			=====           =========                   
			(1)             ccminer.         
			(2)             yam-generic.            
			(3)             cpuminer.         
			(v)             Notas do Autor.             

"

echo -ne "			Your Option: [ ]\033[2D"
read -n 1 opcao
echo -e "\n"
case "$opcao"
in

##########################################
1)
"$BPTH"ccminer.sh
;;
2)
"$BPTH"yam.sh
;;
3)
"$BPTH"cpuminer.sh
;;
v|V)
clear
"$BPTH"gisb
tput bold
read -p "
			Pressione ENTER para Continuar...
"
;;
x|X)
break
;;
*)
echo -e "\033[32;40mOps... So uma das opcoes acima podem ser usadas...\033[0m"
sleep 2
;;
##########################################
esac
exit
