#!/bin/sh
#
#
#	Menu de Para Automatizar o Uso do Sistema.
#
#
#colors
BPTH="/bin/"
echo -ne "				CHOOSE MINER
				------------------------------
			Option          Description                  
			=====           =========                   
			(1)             ccminer         
			(2)             yam            
			(3)             cpuminer         

"

echo -ne "			Your Option: [ ]\033[2D"
read -n 1 opcao
echo -e "\n"
case "$opcao"
in

##########################################
1)
"$BPTH"ccminer.sh
;;
2)
"$BPTH"yam.sh
;;
3)
"$BPTH"cpuminer.sh
;;
*)
echo -e "\033[32;40mOps... So uma das opcoes acima podem ser usadas...\033[0m"
sleep 2
;;
##########################################
esac
exit
