#!/bin/sh
#By: isca
#Ctba 11/11/15
#### This make package for arch-miner

files=""/bin/yam*" "/bin/minerd" "/etc/mkinitcpio.conf" "/lib/initcpio/hooks/mine" "/lib/initcpio/install/network" "/lib/initcpio/install/mine" "/boot/isca.img""
pkg="/root/aminer.tgz"

for file in $files
do
	if [ ! -e $pkg ]
	then
		tar cvf $pkg $file
	fi
	tar rvf $pkg $file
done

exit 0
